PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE pages (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    slug        TEXT    NOT NULL UNIQUE,  -- ex: "cookbook-cod-recomandari-ai"
    url         TEXT,
    chapter_num TEXT,                     -- ex: "04"
    chapter_label TEXT,                   -- ex: "Recomandări inteligente..."
    title       TEXT,
    subtitle    TEXT,
    updated_at  TEXT                      -- ex: "24.02.2026"
);
INSERT INTO pages VALUES(1,'cookbook-cod-recomandari-ai','https://www.opti.ro/ai-2026/ghid-recomandari-upsell/cookbook-cod-recomandari-ai','04','Recomandări inteligente, upsell, bundling și guardrails','Cookbooktehnic','CAPITOLUL04','24.02.2026');
CREATE TABLE sections (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    page_id      INTEGER NOT NULL REFERENCES pages(id),
    sort_order   INTEGER NOT NULL,
    anchor_id    TEXT,                    -- ex: "minimal-complete-ai-pipeline"
    section_type TEXT NOT NULL,          
    -- tipuri: 'hero', 'intro', 'toc', 'content', 'conclusion', 'cta', 'faq', 'chapter_nav', 'pdf_cta'
    heading_num  TEXT,                    -- ex: "4.1"
    heading_supra TEXT,                   -- ex: "PAS CU PAS"
    heading_title TEXT,                   -- ex: "Un flux minimal complet"
    heading_level INTEGER DEFAULT 2       -- 1=H1, 2=H2, 3=H3
);
INSERT INTO sections VALUES(1,1,1,NULL,'intro',NULL,NULL,NULL,2);
INSERT INTO sections VALUES(2,1,2,NULL,'content','','Recomandări inteligente, upsell, bundling și guardrails','',2);
INSERT INTO sections VALUES(3,1,3,'minimal-complete-ai-pipeline','content','4.1','PAS CU PAS','Un flux minimal complet',2);
INSERT INTO sections VALUES(4,1,4,'step-0-business-requirements-setup','content','4.1.1','Pasul 0','Minimul necesar pentru a începe',3);
INSERT INTO sections VALUES(5,1,5,'step-1-data-inventory-connection','content','4.1.2','Pasul 1','Inventarierea și conectarea datelor',3);
INSERT INTO sections VALUES(6,1,6,'step-2-events-insertion-points','content','4.1.3','Pasul 2','Definirea evenimentelor, livrabilelor și a punctelor de inserție',3);
INSERT INTO sections VALUES(7,1,7,'step-3-candidate-retrieval-logic','content','4.1.4','Pasul 3','Generarea candidaților (Retrieval)',3);
INSERT INTO sections VALUES(8,1,8,'step-4-ranking-final-list-generation','content','4.1.5','Pasul 4','Ranking, reguli și generarea listei finale',3);
INSERT INTO sections VALUES(9,1,9,'step-5-ux-integration-fallback-strategy','content','4.1.6','Pasul 5','Integrare în UX și fallback',3);
INSERT INTO sections VALUES(10,1,10,'step-6-ab-testing-feedback-analysis','content','4.1.7','Pasul 6','Testare, analiză și feedback continuu',3);
INSERT INTO sections VALUES(11,1,11,NULL,'content',NULL,NULL,'Pe scurt:',3);
INSERT INTO sections VALUES(12,1,12,'build-custom-implementation-challenges','content','4.2','EXEMPLE DE COD','Provocări și soluții în varianta   Build (custom)',2);
INSERT INTO sections VALUES(13,1,13,'python-sql-guardrails-logic','content','4.2.1','','Guardrails: Siguranța brandului și reguli de excludere',3);
INSERT INTO sections VALUES(14,1,14,'data-ingestion-consistency-models','content','4.2.2','','Ingestie de date și consistență',3);
INSERT INTO sections VALUES(15,1,15,'business-model-router-logic','content','4.2.3','','Alegerea modelului potrivit pentru funcția de business',3);
INSERT INTO sections VALUES(16,1,16,'market-basket-analysis-spark-sql','content','4.2.4','','Bundling și pachete dinamice',3);
INSERT INTO sections VALUES(17,1,17,'managed-cloud-native-configuration','content','4.3','EXEMPLE DE CONFIGURĂRI','Provocări și soluții în varianta   Managed (Cloud Native)',2);
CREATE TABLE blocks (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    section_id   INTEGER NOT NULL REFERENCES sections(id),
    sort_order   INTEGER NOT NULL,
    block_type   TEXT NOT NULL,
    -- tipuri: 'paragraph', 'callout', 'code_example', 'subsection', 
    --         'summary_box', 'link_ref', 'ordered_list', 'unordered_list',
    --         'faq_item', 'chapter_card', 'badge'
    variant      TEXT,
    -- pentru callout: 'build' | 'managed' | 'teal' | 'cream' | 'blue' | 'default'
    -- pentru code_example: limbajul (python, sql, javascript, json, yaml)
    title        TEXT,                    -- titlu opțional al blocului
    content      TEXT,                    -- conținut principal (HTML sau text)
    anchor_id    TEXT,                    -- anchor propriu dacă există
    heading_num  TEXT,                    -- ex: "4.2.1" pentru subsecțiuni
    heading_supra TEXT
);
INSERT INTO blocks VALUES(1,2,1,'paragraph',NULL,NULL,'Știai că sistemele AI au fost create (și) de programatori? Cel puțin pe moment, încă este nevoie de programatori pentru a integra AI cu procesele și software-ul existent. Acest capitol este dedicat celor care vor să vadă cu ochii lor mici bucăți dintr-o asemenea integrare. Dacă ești decident, fluxul minim (dar complet) de implementare din 4.1 este pentru tine. Sau poți sări la capitolul următor.',NULL,NULL,NULL);
INSERT INTO blocks VALUES(2,2,2,'toc',NULL,'Alege ce citești','[{"num": "4.1", "text": "Flux minim complet", "href": "#minimal-complete-ai-pipeline", "tags": ["Business", "Tech", "Product"]}, {"num": "4.1.1", "text": "Minim necesar pentru start", "href": "#step-0-business-requirements-setup", "tags": ["Business", "Sales"]}, {"num": "4.1.2", "text": "Inventariere și conectare date", "href": "#step-1-data-inventory-connection", "tags": ["Tech", "Product"]}, {"num": "4.1.3", "text": "Definire evenimente și inserție", "href": "#step-2-events-insertion-points", "tags": ["Tech", "Product"]}, {"num": "4.1.4", "text": "Retrieval: generare candidați", "href": "#step-3-candidate-retrieval-logic", "tags": ["Tech", "Product"]}, {"num": "4.1.5", "text": "Ranking și listă finală", "href": "#step-4-ranking-final-list-generation", "tags": ["Tech", "Product"]}, {"num": "4.1.6", "text": "Integrare UX și fallback", "href": "#step-5-ux-integration-fallback-strategy", "tags": ["Product", "Business"]}, {"num": "4.1.7", "text": "Testare și feedback continuu", "href": "#step-6-ab-testing-feedback-analysis", "tags": ["Business", "Tech", "Product"]}, {"num": "4.2", "text": "Build: provocări și soluții", "href": "#build-custom-implementation-challenges", "tags": ["Tech", "Product", "Business"]}, {"num": "4.2.1", "text": "Guardrails post-procesare", "href": "#python-sql-guardrails-logic", "tags": ["Tech", "Product"]}, {"num": "4.2.2", "text": "Ingestie date și consistență", "href": "#data-ingestion-consistency-models", "tags": ["Tech", "Product"]}, {"num": "4.2.3", "text": "Alegerea modelului", "href": "#business-model-router-logic", "tags": ["Tech", "Business", "Product"]}, {"num": "4.2.4", "text": "Bundling și pachete dinamice", "href": "#market-basket-analysis-spark-sql", "tags": ["Tech", "Product", "Business"]}, {"num": "4.3", "text": "Managed: provocări și soluții", "href": "#managed-cloud-native-configuration", "tags": ["Business", "Tech", "Product"]}, {"num": "4.3.1", "text": "Placements și filtre", "href": "#managed-placements-filters-guardrails", "tags": ["Business", "Product"]}, {"num": "4.3.2", "text": "Evenimente real-time și intenție", "href": "#real-time-user-events-api", "tags": ["Tech", "Product"]}, {"num": "4.3.3", "text": "Ingestie și experimentare", "href": "#managed-ingestion-ab-testing", "tags": ["Tech", "Product", "Business"]}, {"num": "4.3.4", "text": "Strategii comerciale și bundling", "href": "#commercial-strategies-boost-bury-controls", "tags": ["Business", "Sales", "Product"]}, {"num": "4.4", "text": "TLDR / Concluzie", "href": "#conclusion-how-detailed", "tags": ["Business", "Tech", "Sales", "Product"]}]',NULL,NULL,NULL);
INSERT INTO blocks VALUES(3,2,3,'paragraph',NULL,NULL,unistr('Nu există un câștigător absolut între variantele <i class="fa-regular fa-gear icon-gradient"></i> Build și <i class="fa-regular fa-cloud icon-gradient"></i> \u000d\u000a                    Managed de implementare Deep Learning, pe care le-am comparat în \u000d\u000a                    <a href="/ai-2026/ghid-recomandari-upsell/cum-tehnologie-recomandari-ai/#build-custom-vs-managed-cloud">Cap. 2.4</a>. \u000d\u000a                    În practică, în cazuri diferite, multe companii folosesc o <strong>abordare <i class="fa-regular fa-arrows-left-right icon-gradient"></i> hibridă</strong>.\u000d\u000a                    De exemplu folosesc componente gestionate pentru recomandări de produse, dar implementează custom prognoze temporale sau discounturi inteligente.'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(4,2,4,'paragraph',NULL,NULL,'Fluxul corect de decizie pleacă de la <a href="/ai-2026/ghid-recomandari-upsell/ce-industrii-livrabile-b2b-ai/#ten-practical-ai-deliverables">livrabilele exemplificate în Cap. 3.3.</a>, apoi identifică abordarea tehnică potrivită, apoi estimează efortul necesar.',NULL,NULL,NULL);
INSERT INTO blocks VALUES(5,3,1,'paragraph',NULL,NULL,'Vei trece pas cu pas prin implementarea unui motor de recomandări AI, ca să ai un <strong>blueprint</strong> pentru varianta <i class="fa-regular fa-gear icon-gradient"></i> Build (implementare custom) sau un <strong>checklist</strong> pentru varianta <i class="fa-regular fa-cloud icon-gradient"></i> Managed (Cloud Native).',NULL,NULL,NULL);
INSERT INTO blocks VALUES(6,3,2,'paragraph',NULL,NULL,'În ambele variante, costurile angajate sunt ușor de cuantificat (în special inginerii de date, respectiv consumul Google Cloud), dar ce este invizibil este <strong>costul de oportunitate</strong>: cât costă o implementare slabă care nu va fi folosită. Scopul este să prezentăm <strong>pașii obligatorii pentru succes</strong>.',NULL,NULL,NULL);
INSERT INTO blocks VALUES(7,4,1,'paragraph',NULL,NULL,'Înainte de implementare, compania trebuie să definească:',NULL,NULL,NULL);
INSERT INTO blocks VALUES(8,4,2,'unordered_list',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO blocks VALUES(9,4,3,'callout','build','Build',unistr('<h4>\u000a<i class="fa-regular fa-gear"></i> <strong>Build</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Ședințe cu departamentele de vânzări, marketing, financiar, IT pentru a defini:\u000d\u000a                    </p>\u000a<ul>\u000a<li>\u000a<strong>1-2 scenarii pilot</strong> (ex:"upsell în ofertare", "recomandare în pagina de produs").\u000d\u000a                        </li>\u000a<li>\u000d\u000a                            Un set minim de <strong>guardrails</strong> (marje, stocuri, compatibilități).\u000d\u000a                        </li>\u000a<li>\u000d\u000a                            Colectarea de <strong>feedback</strong>, mai ales <strong>negativ</strong> (ex: "nu mă interesează această recomandare", "această recomandare nu a condus la nicio vânzare timp de o lună").\u000d\u000a                        </li>\u000a</ul>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(10,4,4,'callout','managed','Managed',unistr('<h4>\u000a<i class="fa-regular fa-cloud"></i> <strong>Managed</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Aceleași procese ca în varianta <i class="fa-regular fa-gear"></i> Build.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Se adaugă:\u000d\u000a                    </p>\u000a<ul>\u000a<li>\u000a<strong>Cunoașterea obiectivelor</strong> definibile în dashboard (ex: maximizează CTR / CVR / Revenue).\u000d\u000a                        </li>\u000a<li>\u000d\u000a                            Pregătirea segmentelor de trafic pentru <strong>testele A/B</strong>.\u000d\u000a                        </li>\u000a<li>\u000d\u000a                            Definirea <strong>regiunii</strong>. \u000d\u000a                            În acest moment pentru <em>Vertex AI Search</em> se poate selecta EU Multi-region, \u000d\u000a                            pentru <em>Vertex AI Search for commerce</em> locația este globală. \u000d\u000a                        </li>\u000a<li>\u000d\u000a                            Definirea <strong>regulilor</strong> de date și procese. Ex: ISO27001, NIS2, domenii reglementate.\u000d\u000a                         </li>\u000a</ul>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(11,5,1,'paragraph',NULL,NULL,unistr('Sistemul de recomandări are nevoie de cel puțin trei tipuri de date detaliate în <a href="/ai-2026/ghid-recomandari-upsell/cum-tehnologie-recomandari-ai/#real-time-data-ingestion-api">Cap. 2.3.2</a>: <strong>catalogul de produse, istoricul de interacțiuni</strong> cu clientul și <strong>evenimente continue (ex: clickstream)</strong>.\u000d\u000a                    Ne concentrăm pe primele două.'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(12,5,2,'callout','build','Build',unistr('<h4>\u000a<i class="fa-regular fa-gear"></i> <strong>Build</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Identifici <strong> sursele</strong>: ERP, WMS, CRM, e-commerce, fișiere Excel esențiale.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Definești <strong> schema de date unificată</strong> (ID produs unic, mapping între codurile din ERP, CRM și e-commerce, planul de normalizare unități de măsură etc.).\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Realizezi\u000d\u000a                        <strong> curățarea și normalizarea datelor,</strong>\u000d\u000a                        cum am recomandat în <a href="/ai-2026/ghid-recomandari-upsell/cum-tehnologie-recomandari-ai/#data-quality-consistency-gigo">Cap. 2.5.2</a>.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Construiești un\u000d\u000a                        <strong> pipeline <code>ETL</code>/<code>ELT</code></strong>\u000d\u000a                        (ex: în BigQuery sau alt data warehouse) pentru:\u000d\u000a                    </p>\u000a<ul>\u000a<li>Import de catalog o dată pe zi (full) + incremental în funcție de nevoie.</li>\u000a<li>Filtre de bază pentru <strong>pre-procesare</strong> (ex:  exclude produsele fără stoc 3 luni).</li>\u000a<li>Import cvasi-continuu evenimente de comandă / trafic (streaming sau batch).</li>\u000a</ul>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(13,5,3,'callout','managed','Managed',unistr('<h4>\u000a<strong><i class="fa-regular fa-cloud"></i> Managed</strong>\u000a</h4>\u000a<p>\u000a<strong>Curățarea și normalizarea datelor</strong> proprii este obligatorie și în acest caz.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        În loc să construiești <strong><code>ETL</code></strong> complet, folosești conectori și feed-uri standard:\u000d\u000a                    </p>\u000a<ul>\u000a<li>\u000d\u000a                            Feed de <strong>catalog</strong> (<code>API</code>/CSV/<code>JSON</code>) mapat pe <strong>schema strictă</strong> a Google. \u000d\u000a                            Dacă folosești BigQuery ca data warehouse, poți conecta direct datele.\u000d\u000a                        </li>\u000a<li>\u000a<strong>Regulile de business</strong> pot fi definite inițial ca feed-uri: liste de produse de promovat, excluse, bundle-uri, apoi legate prin consolă sau configuri.\u000d\u000a                        </li>\u000a<li>\u000d\u000a                            Pregătești feedul de <strong>evenimente</strong>: server-side events, Google Tag Manager, loguri.\u000d\u000a                        </li>\u000a<li>\u000d\u000a                            Atenție, librăriile de cod și endpoint-urile API folosesc încă terminologia istorică <strong>Retail</strong> (ex: <code>google.cloud.retail_v2</code>). \u000d\u000a                            \u000d\u000a                        </li>\u000a</ul>\u000a<p>\u000d\u000a                            Pentru B2B, dacă prețurile diferă per client, Vertex AI poate învăța pe prețul de listă, iar aplicația trebuie să aplice prețul corect.\u000d\u000a                            Există în <em>Vertex AI Search for commerce</em> suport pentru <strong>prețuri diferite per segment de clienți</strong>,\u000d\u000a                            cu inginerie de date complexă.                            \u000d\u000a                        </p>\u000a<p>\u000a<strong>Recomandare</strong>: chiar și în varianta <i class="fa-regular fa-cloud"></i> Managed, păstrează o copie a datelor într-un data warehouse (ex: BigQuery) pentru audit și pentru a avea <strong>sursa proprie de adevăr comercial</strong>.\u000d\u000a                    </p>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(14,6,1,'paragraph',NULL,NULL,'Nu poți optimiza ceea ce nu măsori. Compania trebuie să standardizeze evenimentele care descriu <strong>comportamentul utilizatorilor</strong>.',NULL,NULL,NULL);
INSERT INTO blocks VALUES(15,6,2,'paragraph',NULL,NULL,unistr('<summary class="ais_codeblock__summary">\u000d\u000a                            Tipuri de evenimente <em>Vertex AI Search for commerce API</em>. <a href="/ai-2026/ghid-recomandari-upsell/resurse-si-glosar-ai-b2b/#whitepapers-and-studies">Verifică documentația oficială</a>\u000a</summary>\u000a<p>\u000a<strong>Descoperire</strong>: search, detail-page-view, category-page-view, home-page-view, shopping-cart-page-view.\u000d\u000a                    </p>\u000a<p>\u000a<strong>Tranzacționale</strong>: add-to-cart, remove-from-cart, purchase-complete.\u000d\u000a                    </p>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(16,6,3,'paragraph',NULL,NULL,'Trebuie apoi decise în ce <strong>livrabile software concrete</strong> (<a href="/ai-2026/ghid-recomandari-upsell/ce-industrii-livrabile-b2b-ai/#ten-practical-ai-deliverables">Vezi Cap. 3.3</a>) vei insera recomandările AI. Acestea îți dau <strong>punctele de inserție</strong>. De exemplu în UI e-commerce, poți afișa recomandările în: homepage, categorie, pagină de produs, coș, ofertă PDF, e-mail, backend administrativ (pentru echipa de suport).',NULL,NULL,NULL);
INSERT INTO blocks VALUES(17,6,4,'paragraph',NULL,NULL,unistr('<summary class="ais_codeblock__summary">  Riscuri de date în B2B  </summary>\u000a<ul>\u000a<li>\u000d\u000a                            În B2B cheia de tracking pentru indicatori <strong>nu este individuală</strong> ca în B2C, ci contractul, clientul (account sau organizație) sau grupul de clienți.\u000d\u000a                        </li>\u000a<li>\u000d\u000a                            În B2B tranzacțiile fiind de dimensiuni mari dar rare, pierderea unui eveniment din tracking poate fi catastrofală. Folosește mecanisme de <strong>reîncercare și idempotență</strong>.\u000d\u000a                        </li>\u000a<li>\u000d\u000a                            Recomandăm <strong>pseudo-anonimizarea (ex: hashing)</strong> datelor personale înainte de a le trimite în sistemul de recomandări. Păstrezi consistența cu risc de conformitate redus.\u000d\u000a                        </li>\u000a<li>\u000d\u000a                            Pentru explicabilitate și audit, se recomandă să <strong>logați toate interacțiunile de date</strong> cu sistemul de recomandări. Așa veți putea reconstrui separat în viitor KPI-uri tehnice ca NDCG@k (relevanța ordonării) și Recall@k (relevanța căutării).\u000d\u000a                        </li>\u000a</ul>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(18,6,5,'callout','build','Build',unistr('<h4>\u000a<i class="fa-regular fa-gear"></i> <strong>Build</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Definești o <strong>schemă de evenimente</strong> (nume, payload de date, id-uri unice coerente). Implementezi logarea lor din aplicațiile existente ale companiei:\u000d\u000a                    </p>\u000a<ul>\u000a<li>Scripturi JS pentru site e-commerce.</li>\u000a<li>Hooks în backend e-commerce, ERP, WMS sau CRM.</li>\u000a<li>Logare în fișiere sau în topicuri (ex. Pub/Sub, Kafka).</li>\u000a</ul>\u000a<p>\u000d\u000a                        Stabilești cum va primi la final aplicația <strong>recomandările</strong>:\u000d\u000a                    </p>\u000a<ul>\u000a<li>\u000d\u000a                            Endpoint <code>API POST /recom Account_id=…&amp;Context=…</code>\u000a</li>\u000a<li>\u000d\u000a                            Widget pe site e-commerce sau în aplicații interne.\u000d\u000a                        </li>\u000a</ul>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(19,6,6,'callout','managed','Managed',unistr('<h4>\u000a<strong><i class="fa-regular fa-cloud"></i> Managed</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Mapezi evenimentele tale în <strong>schema strictă</strong> a Google. Dacă ai evenimentele în BigQuery \u000d\u000a                        sau Google Tag Manager, le poți conecta direct.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Configurezi <strong>ServingConfigs</strong> pentru fiecare <strong>punct de inserție</strong> (en. <em>placement</em>) pe care îl definești în aplicațiile tale (ex: homepage_recs, cart_upsell).\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Un <strong>ServingConfig</strong> include:\u000d\u000a                    </p>\u000a<ul>\u000a<li><strong>Modelul</strong> selectat din lista Google. Ex: <em>Buy it Again</em> cu obiectivul de maximizat deja selectat.</li>\u000a<li><strong>Serving Controls</strong>. <em>Filter</em> (excludere - doar în varianta de căutare), <em>Boost</em> (promovare), <em>Bury</em> (retrogradare).</li>\u000a<li>Setarea de <strong>diversitate</strong>: cât de non-repetitive sunt recomandările.</li>\u000a<li>Chemi un <strong>ServingConfig</strong> când apelezi API, deci îl poți folosi pentru mai multe puncte de inserție în aplicațiile companiei dacă au aceleași reguli.</li>\u000a<li>Serving Controls pot fi <strong>realizate ca fișiere JSON</strong>, deci refolosite în ServingConfigs de căutare diferite.</li>\u000a</ul>\u000a<p>\u000d\u000a                        Atenție, în versiuni mai vechi, se defineau obiecte de tip <em>Placement</em>, dar acestea nu sunt recomandate în noul API pentru <em>Vertex AI Search for Commerce</em> (retail_v2).\u000d\u000a                    </p>\u000a<p>\u000a<strong>Beneficiul</strong> este că nu vei implementa de la zero. Dar trebuie să decizi ce înseamnă <strong>succesul</strong> pentru fiecare punct de inserție, plus să inserezi <strong>date istorice (minim 3 luni recomandat)</strong> pentru ca algoritmul să nu plece de la zero.\u000d\u000a                    </p>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(20,7,1,'paragraph',NULL,NULL,unistr('Primul pas tehnic al sistemului de recomandări va fi să găsească <strong>candidații potențiali</strong>: zeci sau sute de produse care sunt relevante.\u000d\u000a                    Aceasta este faza <em>Retrieval</em> din arhitectura descrisă în <a href="/ai-2026/ghid-recomandari-upsell/cum-tehnologie-recomandari-ai/#two-tower-model-retrieval-ranking">Cap. 2.3.1</a>.'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(21,7,2,'callout','build','Build',unistr('<h4>\u000a<i class="fa-regular fa-gear"></i> <strong>Build</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Configurezi un motor de <strong>căutare lexicală (<code>BM25</code> / full-text)</strong> pe catalog și \u000d\u000a                        în paralel un motor de <strong>căutare vectorială</strong> cu embeddings pentru produse, clienți, secvențe de sesiuni.\u000d\u000a\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Implementezi opțional un modul de <strong>pre-procesare bazată pe reguli</strong>: tip de client, stoc, evitare produse nerelevante.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Rezultatul obținut de <strong><code>Vector Search</code></strong> este o listă de candidați care merg apoi la <strong>Scoring</strong>.\u000d\u000a                    </p>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(22,7,3,'callout','managed','Managed',unistr('<h4>\u000a<i class="fa-regular fa-cloud"></i><strong> Managed</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Oferă Retrieval <strong>nativ</strong> pe baza evenimentelor, pe baza conținutului (content-based / deep attribution: atribute, fișă produs, inclusiv imagine)\u000d\u000a                        și pe baza asocierilor. \u000d\u000a                    </p>\u000a<p>\u000d\u000a                         Pentru <strong>upsell și cross-sell</strong>, se folosesc de obicei inginerie de date și <em>Collections</em>: la fiecare produs \u000d\u000a                         poți trimite oricâte ID-uri de pachete (compatibile, bundle) care îl conțin, iar modelul va transfera relevanța.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        În consolă poți defini <strong>noi sinonime</strong> (ex: poți defini "cut" ca fiind "cutie") și mai ales filtrele (ex: doar produse în stoc, doar acest brand / categorie) sau strategiile de diversitate ("nu recomanda doar ce e ultra-popular").\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Nu construiești algoritmi de recomandare, dar trebuie <strong>atenție la configurare și inginerie de date</strong>.\u000d\u000a                    </p>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(23,7,4,'link_ref',NULL,NULL,'Vezi Ghidul #4 pentru combinarea căutării lexicale cu cea semantică','/ai-2026/ghid-cautare-hibrida/',NULL,NULL);
INSERT INTO blocks VALUES(24,8,1,'paragraph',NULL,NULL,'Conține pașii cei mai complecși tehnic. Pentru ranking, modelele AI de scoring vor face:',NULL,NULL,NULL);
INSERT INTO blocks VALUES(25,8,2,'ordered_list',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO blocks VALUES(26,8,3,'callout','build','Build',unistr('<h4>\u000a<i class="fa-regular fa-gear"></i>\u000a<strong>Build</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Antrenezi și apelezi un <strong>model de ranking</strong> (ex. tip <em>learning to rank</em>) care primește:\u000d\u000a                    </p>\u000a<ul>\u000a<li>\u000d\u000a                            semnale din <strong>catalog</strong>: preț, marjă, categorie, compatibilitate.\u000d\u000a                        </li>\u000a<li>\u000d\u000a                            semnale de <strong>context</strong>: tip client, timp, detalii coș / ofertă.\u000d\u000a                        </li>\u000a</ul>\u000a<p>\u000d\u000a                        Aplici regulile de business în <strong>post-procesare</strong> (ex: Python, <em>rule engines</em> ca Drools):\u000d\u000a                    </p>\u000a<ul>\u000a<li>Filtrează produse fără stoc sau sub marja minimă.</li>\u000a<li>Promovează anumite produse sau campanii.</li>\u000a<li>Asigură deduplicare și diversitate. Ex: "fără 3 produse consecutive de la același brand".</li>\u000a</ul>\u000a<p>\u000d\u000a                        Testezi capacitatea de scalare și optimizezi pentru <strong>latență redusă</strong>: caching, optimizări de model.\u000d\u000a                    </p>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(27,8,4,'callout','managed','Managed',unistr('<h4>\u000a<i class="fa-regular fa-cloud"></i><strong> Managed</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Alegi inițial <strong>obiective și parametri de ranking</strong>:  "optimizează pentru click pe recomandare" / "optimizează pentru venit per sesiune" / "optimizează pentru conversie". \u000d\u000a \u000d\u000a                        Odată antrenat, un model cu obiectiv de maximizat selectat nu poate fi schimbat, va trebui să-l re-antrenezi dacă dorești să schimbi obiectivul.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Poți configura și <strong>intervalul de training</strong> al modelului.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Rafinezi <strong>regulile de business</strong> ca Filters / Boost /  Bury (Serving Controls). \u000d\u000a                        Pentru a obține efectele dorite, este nevoie de creativitate și inginerie de date solidă: \u000d\u000a                    </p>\u000a<ul>\u000a<li>\u000d\u000a                            Fiecare control are structura de condiție / efect (ex: în CEL - Common Expression Language).\u000d\u000a                            Ceea ce te reîntoarce la definirea schemei.\u000d\u000a                        </li>\u000a<li>\u000d\u000a                            De exemplu, pentru a implementa o regulă de prognoză temporală externă, \u000d\u000a                            poți crea în schemă un atribut <code>seasonal_score</code> (ex: 0.0-1.0) și apoi să definești un Boost.                         \u000d\u000a                        </li>\u000a<li>Atenție, adesea rămân unele reguli în middleware sau aplicație, de exemplu <strong>permisiunile</strong>.                     </li>\u000a</ul>\u000a<p>\u000a<strong>Scalarea automată</strong> în cloud la vârf de încărcare (ex: Black Friday) este de obicei un avantaj.\u000d\u000a                    </p>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(28,8,5,'link_ref',NULL,NULL,'Vezi Ghidul #5 - Optimizare continuă, raportare și feedback','/ai-2026/ghid-optimizare-feedback-loop/',NULL,NULL);
INSERT INTO blocks VALUES(29,9,1,'paragraph',NULL,NULL,unistr('Motorul de recomandări AI trebuie conectat invizibil (en. <em>seamless</em>) cu <strong>aplicația software</strong> (ex: e-commerce). \u000d\u000a                    Trebuie și să permită <strong>feedback</strong> și să asigure <strong>comportament previzibil</strong> pentru clienții sau agenții de vânzări care beneficiază.'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(30,9,2,'callout','build','Build',unistr('<h4>\u000a<i class="fa-regular fa-gear"></i>\u000a<strong>Build</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Un <strong>microserviciu</strong> dedicat cu <code>API</code> va întoarce lista finală de recomandări.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Construiești o <strong>componentă UI</strong> care afișează recomandările (ex. site e-commerce).\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Definești varianta elegantă (en. <em>graceful</em>) de <strong>fallback</strong>. Ce se vede când <code>API</code>-ul nu răspunde / nu are recomandări - de exemplu se poate rula o interogare <code>SQL</code> pentru cele mai noi produse.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Implementezi un mecanism de <strong>feedback explicit</strong> (<em>Thumbs up/down</em> sau <em>Ascunde</em>).\u000d\u000a                        La re-antrenare acest semnal trebuie să fie mult mai puternic decât simpla ignorare a recomandării.\u000d\u000a                    </p>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(31,9,3,'callout','managed','Managed',unistr('<h4>\u000a<strong><i class="fa-regular fa-cloud"></i> Managed</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Trimiți outputul în aplicație <strong>programatic</strong> (via <code>API</code>/<code>SDK</code>) sau encapsulezi (en. <em>embed</em>)\u000d\u000a                         unele <strong>mini-aplicații</strong> disponibile în <em>Vertex AI Search for commerce</em>  (ex: widget-uri frontend, via <code>JS</code>).\u000d\u000a                         </p>\u000a<p>În primul caz, construiești componenta UI ca în varianta <i class="fa-regular fa-gear"></i> Build.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Prevezi <strong>fallback</strong> ca în varianta Build, pentru a nu avea interfață goală niciodată (necesar dacă folosești varianta <code>API</code>). \u000d\u000a                        Dacă folosești widget-urile Google, acestea au deja mecanisme de fallback integrate și în varianta API există un parametru <code>strictFiltering</code> \u000d\u000a                        care poate fi setat ca fals pentru a returna recomandări când filtrele ar elimina rezultatele.\u000d\u000a                       </p>\u000a<p> Prevezi mecanismele de <strong>feedback explicit</strong>.\u000d\u000a                        De obicei, <em>Vertex AI Search for commerce</em> colectează  feedback implicit (clickuri, conversii).\u000d\u000a                        <strong>Feedbackul negativ</strong> trebuie implementat de la caz la caz. Poți folosi Filter / Bury sau chiar un eveniment de îndepărtare din coș. În aplicație poți folosi inginerie de date \u000d\u000a                        pentru a filtra produsele trimise către AI sau cele returnate de AI. \u000d\u000a                    </p>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(32,10,1,'paragraph',NULL,NULL,'Un sistem de recomandări robust depinde de testare A/B și de mentenanță continuă după livrare. Monitorizezi <strong>KPI-urile</strong>, <strong>anomaliile</strong> (ex: raport al calității) și <strong>feedback-ul</strong> clienților sau companiei.',NULL,NULL,NULL);
INSERT INTO blocks VALUES(33,10,2,'paragraph',NULL,NULL,unistr('<strong>Shadow mode</strong> (rularea recomandărilor AI pentru publicul intern înainte de a lansa pentru clienți) permite validarea algoritmului pe date reale fără a risca veniturile sau imaginea.\u000d\u000a                    Similar, o procedură de <strong>backtesting</strong> rulează algoritmul pe date istorice, eventual completate din urmă (en. <em>backfill</em>), înainte de orice rulare live.'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(34,10,3,'callout','build','Build',unistr('<h4>\u000a<i class="fa-regular fa-gear"></i>\u000a<strong>Build</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Configurezi <strong><code>A/B testing</code></strong> (in-house sau printr-o platformă SaaS, de exemplu split.io):\u000d\u000a                    </p>\u000a<ul>\u000a<li>Grup A = situația precedentă.</li>\u000a<li>Grup B = aplicare algoritmi noi.</li>\u000a</ul>\u000a<p><strong>Compari KPI</strong> (de obicei de business): AOV, rată de acceptare recomandări, timp de ofertare.</p>\u000a<p>\u000d\u000a                        După validare și <strong>lansare</strong>, implementezi <strong>dashboarduri de analiză</strong> (ex. Grafana / Looker Studio) pentru un raport al calității:\u000d\u000a                    </p>\u000a<ul>\u000a<li>Evoluția KPI-urilor de business (vezi mai sus).</li>\u000a<li>\u000d\u000a                            Distribuția statistică a recomandărilor: procent bestsellers, diversitate per brand /  preț / categorie.\u000d\u000a\u000d\u000a                        </li>\u000a<li>Intervențiile regulilor de business (guardrails) și al mecanismelor de fallback</li>\u000a</ul>\u000a<p>\u000d\u000a                        La modificări de algoritm, rulezi <strong>backtesting</strong> (testare pe date vechi) și <strong>shadow</strong> mode (testare internă în paralel cu sistemul existent).\u000d\u000a                    \u000a</p>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(35,10,4,'callout','managed','Managed',unistr('<h4>\u000a<i class="fa-regular fa-cloud"></i><strong> Managed</strong>\u000a</h4>\u000a<p>\u000d\u000a                        Pentru <strong>A/B</strong> folosești <strong>experimentele</strong> <em>Vertex AI Search for commerce</em>:\u000d\u000a                    </p>\u000a<ul>\u000a<li>Schimbi obiectivele și strategiile fără a modifica codul programat.</li>\u000a<li>Analizezi rezultatele în dashboarduri vizuale.</li>\u000a<li>Ajustezi în funcție de KPI (de obicei de business).</li>\u000a</ul>\u000a<p>\u000d\u000a                        Pentru <strong>analiză</strong>, există rapoarte și metrici vizuale în platformă: CTR, conversion rate, revenue per session.   Se pot configura dashboarduri custom ca în varianta Build, de ex. în Looker Studio.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Poți rula experimente de tip <strong>shadow mode</strong> pe un nou model care nu este în producție, pentru a vedea intern rezultatele.\u000d\u000a                    </p>\u000a<p>\u000d\u000a                        Poți experimenta inclusiv <strong>înlocuirea treptată</strong> a regulilor configurate de Boost / Bury / Filter \u000d\u000a                        cu cele auto-calculate de modelul AI (pe măsura efectelor pozitive).\u000d\u000a                    </p>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(36,10,5,'paragraph',NULL,NULL,unistr('Dacă ai trecut cu succes prin acești pași minimali, ai schițat un sistem de recomandări complet.\u000d\u000a    Ai aflat că <strong>recomandările AI nu sunt un black box magic</strong>, ci o structură din sistemul de vânzări al companiei, în care <strong>datele, regulile și oamenii</strong> sunt esențiali.'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(37,11,1,'callout','teal','',unistr('<ul>\u000a<li>\u000a<strong>\u000d\u000a                                Deep Learning nu este un singur proces, ci o succesiune de pași:\u000d\u000a                            </strong>\u000d\u000a\u000d\u000a                            definirea obiectivelor, curățarea și conectarea datelor, definirea evenimentelor,\u000d\u000a                            generarea candidaților, ranking și post-procesare, integrare în UX, feedback explicit, monitorizare.\u000d\u000a\u000d\u000a                        </li>\u000a<li>\u000a<strong>\u000a<i class="fa-regular fa-gear icon-gradient"></i> Build (custom)\u000d\u000a                            </strong>\u000d\u000a\u000d\u000a                            oferă control maxim, dar cere echipă tehnică dedicată și disciplinată, în plus față de\u000d\u000a                            efortul întregii companii.\u000d\u000a\u000d\u000a                        </li>\u000a<li>\u000a<strong>\u000a<i class="fa-regular fa-cloud icon-gradient"></i> Managed (Cloud Native)\u000d\u000a                            </strong>\u000d\u000a\u000d\u000a                            externalizează o parte din complexitate, dar necesită decizii la nivelul companiei și\u000d\u000a                            configurare tehnică atentă.\u000d\u000a\u000d\u000a                        </li>\u000a<li>\u000d\u000a\u000d\u000a                            Ambele variante depind de curățarea datelor și <code>A/B testing</code> pentru a obține rezultate.\u000d\u000a\u000d\u000a                        </li>\u000a</ul>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(38,12,1,'paragraph',NULL,NULL,unistr('Prezentăm fragmente de cod pentru o implementare de tip Build (custom) de Deep Learning. Cele patru scenarii corespund\u000d\u000a                    provocărilor de business din <a href="/ai-2026/ghid-recomandari-upsell/cum-tehnologie-recomandari-ai/#business-guardrails-data-contract">Cap. 2.5:\u000d\u000a                    guardrails și contract de date</a>, dar și provocărilor tehnice din <a href="/ai-2026/ghid-recomandari-upsell/cum-tehnologie-recomandari-ai/#technical-fine-tuning-challenges">Cap. 2.6: modele pe funcții de business și bundling</a>.'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(39,12,2,'callout','build','',unistr('<p><strong>Note</strong></p>\u000a<ul>\u000a<li>\u000d\u000a                            Exemplele sunt în pseudocod, pentru a <strong>arăta în practică</strong> câteva bucăți cheie de logică recomandări AI.\u000d\u000a                        </li>\u000a<li>\u000d\u000a                            Pentru volume mari de date (Big Data) logica tinde să se mute din <strong><code>Python</code></strong> în <strong><code>Spark</code></strong> sau <strong><code>SQL</code></strong>\u000d\u000a                            pentru a evita iterări pe milioane de produse. Vezi exemple la <a href="#market-basket-analysis-spark-sql">Cap 4.2.4</a>.\u000d\u000a                        </li>\u000a<li>\u000a<em>Exemplele de cod sunt simplificate pentru claritate și necesită adaptare la mediul de producție specific, plus <strong>autentificare/IAM, protecție pentru concurență, excepții, reîncercări</strong> etc.</em>\u000a</li>\u000a</ul>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(40,13,1,'paragraph',NULL,NULL,'AI a produs un <strong>scor brut</strong> pentru fiecare candidat, iar guardrails trebuie să asigure că nu vindem produse sub marja minimă sau fără stoc și nu lăsăm UI-ul gol dacă <code>API</code>-urile nu funcționează.',NULL,NULL,NULL);
INSERT INTO blocks VALUES(41,13,2,'code_example',NULL,'Exemplu B1: Filtrare în pipeline-ul de recomandare ( Python )',NULL,NULL,NULL,NULL);
INSERT INTO blocks VALUES(42,13,3,'code_example',NULL,'Exemplu B2: Validare de calitate candidați la nivel de tabel ( SQL )',NULL,NULL,NULL,NULL);
INSERT INTO blocks VALUES(43,14,1,'code_example',NULL,'Exemplu B3: Model de eveniment ( Python )',NULL,NULL,NULL,NULL);
INSERT INTO blocks VALUES(44,14,2,'code_example',NULL,'Exemplu B4: Upsert pentru stoc ( SQL )',NULL,NULL,NULL,NULL);
INSERT INTO blocks VALUES(45,14,3,'code_example',NULL,'Exemplu B5: Verificare a consistenței stocului ( SQL )',NULL,NULL,NULL,NULL);
INSERT INTO blocks VALUES(46,15,1,'paragraph',NULL,NULL,unistr('Reamintim din <a href="/ai-2026/ghid-recomandari-upsell/cum-tehnologie-recomandari-ai/#model-business-fit">Cap. 2.6.1</a> că nu există un singur model magic de recomandări. În practică, ai un model pentru <em>Similare</em>,\u000d\u000a                    un altul pentru <em>Cumpărate împreună</em>, poate altul pentru <em>Cumpără din nou</em>, plus modele speciale.'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(47,15,2,'code_example',NULL,'Exemplu B6: Router simplu de modele ( Python )',NULL,NULL,NULL,NULL);
INSERT INTO blocks VALUES(48,15,3,'code_example',NULL,'Exemplu B7: Config declarativ pentru scenarii',NULL,NULL,NULL,NULL);
INSERT INTO blocks VALUES(49,16,1,'callout','default','',unistr('<p>\u000d\u000a\u000d\u000a                        Bundling-ul poate apărea în două locuri:\u000d\u000a\u000d\u000a                    </p>\u000a<ul>\u000a<li>\u000d\u000a\u000d\u000a                            În\u000d\u000a\u000d\u000a                            <strong>\u000d\u000a                                sistemul de recomandare:\u000d\u000a                            </strong>\u000d\u000a\u000d\u000a                            ce pachet propun pentru coșul sau oferta curentă.\u000d\u000a\u000d\u000a                        </li>\u000a<li>În <strong>data warehouse</strong>: ce propuneri recomandăm să devină pachete permanente în aplicație.</li>\u000a</ul>'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(50,16,2,'paragraph',NULL,NULL,unistr('Într-o situație de producție cu milioane de tranzacții istorice, iterarea simplă (ex: <code>Python</code>) este ineficientă combinatoric (en. <em>combinatorial explosion</em>).\u000d\u000a                    Se folosesc clustere de date (ex: <code>Databricks</code>, <code>Spark</code>) pentru a căuta asocierile de forma "cine cumpără A, cumpără și B cu probabilitatea X".'),NULL,NULL,NULL);
INSERT INTO blocks VALUES(51,16,3,'code_example',NULL,'Exemplu B8: Calcul reguli de asociere cu  Spark  ( PySpark )',NULL,NULL,NULL,NULL);
INSERT INTO blocks VALUES(52,16,4,'code_example',NULL,'Exemplu B9: Rafinare pachete asociate după marjă și stoc ( Spark   SQL )',NULL,NULL,NULL,NULL);
INSERT INTO blocks VALUES(53,16,5,'code_example',NULL,'Exemplu B10: Aplicare bundle în momentul ofertării ( Python )',NULL,NULL,NULL,NULL);
INSERT INTO blocks VALUES(54,16,6,'paragraph',NULL,NULL,'În plus față de codare, în abordarea Build este <strong>esențială infrastructura de servere, pipeline-urile de date și monitorizarea lor</strong>.',NULL,NULL,NULL);
INSERT INTO blocks VALUES(55,16,7,'link_ref',NULL,NULL,'Studiu de caz: Infrastructură AI-Ready (web, email, vânzări)','/case-study/studiu-caz-infrastructura-ai-ready-web-email-vanzari/',NULL,NULL);
INSERT INTO blocks VALUES(56,16,8,'paragraph',NULL,NULL,'În secțiunea următoare, vedem cum Google preia o parte din muncă prin configurarea abordării <i class="fa-regular fa-cloud icon-gradient"></i> Managed.',NULL,NULL,NULL);
INSERT INTO blocks VALUES(57,17,1,'link_ref',NULL,NULL,'Studiu de caz: Integrare ERP Entersoft-Vertex AI Search pentru distribuție','/case-study/studiu-caz-entersoft-erp-ai-vanzari-distributie/',NULL,NULL);
CREATE TABLE elements (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    block_id     INTEGER NOT NULL REFERENCES blocks(id),
    sort_order   INTEGER NOT NULL,
    element_type TEXT NOT NULL,
    -- tipuri: 'list_item', 'note_item', 'link', 'code_snippet', 
    --         'summary_item', 'faq_answer', 'chapter_nav_item'
    content      TEXT,
    href         TEXT,                    -- pentru link-uri
    label        TEXT,                    -- text afișat pentru link
    extra        TEXT                     -- JSON pentru date extra (ex: tag-uri, atribute)
);
INSERT INTO elements VALUES(1,8,1,'list_item','<strong>Obiectivele de business</strong>: ce vrei să îmbunătățești (AOV, rata de conversie, marja, vânzarea produselor slow-moving). Vezi <a href="/ai-2026/ghid-recomandari-upsell/cum-tehnologie-recomandari-ai/#measuring-ai-success-kpis">Cap. 2.2.</a>',NULL,NULL,NULL);
INSERT INTO elements VALUES(2,8,2,'list_item','<strong>KPI măsurabili</strong>: indicatorii companiei (lunari sau trimestriali) și tehnologici (ex: latență și fallback).',NULL,NULL,NULL);
INSERT INTO elements VALUES(3,8,3,'list_item','<strong>Reguli de business</strong>: ce trebuie să respecte AI (fără halucinații de preț, stoc sau compatibilități, marjă minimă, reguli de diversitate brand, excluderi de clienți rău-platnici). Vezi <a href="/ai-2026/ghid-recomandari-upsell/cum-tehnologie-recomandari-ai/#ai-control-post-processing-rules">Cap. 2.5.1</a>',NULL,NULL,NULL);
INSERT INTO elements VALUES(4,9,1,'list_item','<strong>1-2 scenarii pilot</strong> (ex:"upsell în ofertare", "recomandare în pagina de produs").',NULL,NULL,NULL);
INSERT INTO elements VALUES(5,9,2,'list_item','Un set minim de <strong>guardrails</strong> (marje, stocuri, compatibilități).',NULL,NULL,NULL);
INSERT INTO elements VALUES(6,9,3,'list_item','Colectarea de <strong>feedback</strong>, mai ales <strong>negativ</strong> (ex: "nu mă interesează această recomandare", "această recomandare nu a condus la nicio vânzare timp de o lună").',NULL,NULL,NULL);
INSERT INTO elements VALUES(7,10,1,'list_item','<strong>Cunoașterea obiectivelor</strong> definibile în dashboard (ex: maximizează CTR / CVR / Revenue).',NULL,NULL,NULL);
INSERT INTO elements VALUES(8,10,2,'list_item','Pregătirea segmentelor de trafic pentru <strong>testele A/B</strong>.',NULL,NULL,NULL);
INSERT INTO elements VALUES(9,10,3,'list_item',unistr('Definirea <strong>regiunii</strong>. \u000d\u000a                            În acest moment pentru <em>Vertex AI Search</em> se poate selecta EU Multi-region, \u000d\u000a                            pentru <em>Vertex AI Search for commerce</em> locația este globală.'),NULL,NULL,NULL);
INSERT INTO elements VALUES(10,10,4,'list_item','Definirea <strong>regulilor</strong> de date și procese. Ex: ISO27001, NIS2, domenii reglementate.',NULL,NULL,NULL);
INSERT INTO elements VALUES(11,12,1,'list_item','Import de catalog o dată pe zi (full) + incremental în funcție de nevoie.',NULL,NULL,NULL);
INSERT INTO elements VALUES(12,12,2,'list_item','Filtre de bază pentru <strong>pre-procesare</strong> (ex:  exclude produsele fără stoc 3 luni).',NULL,NULL,NULL);
INSERT INTO elements VALUES(13,12,3,'list_item','Import cvasi-continuu evenimente de comandă / trafic (streaming sau batch).',NULL,NULL,NULL);
INSERT INTO elements VALUES(14,13,1,'list_item',unistr('Feed de <strong>catalog</strong> (<code>API</code>/CSV/<code>JSON</code>) mapat pe <strong>schema strictă</strong> a Google. \u000d\u000a                            Dacă folosești BigQuery ca data warehouse, poți conecta direct datele.'),NULL,NULL,NULL);
INSERT INTO elements VALUES(15,13,2,'list_item','<strong>Regulile de business</strong> pot fi definite inițial ca feed-uri: liste de produse de promovat, excluse, bundle-uri, apoi legate prin consolă sau configuri.',NULL,NULL,NULL);
INSERT INTO elements VALUES(16,13,3,'list_item','Pregătești feedul de <strong>evenimente</strong>: server-side events, Google Tag Manager, loguri.',NULL,NULL,NULL);
INSERT INTO elements VALUES(17,13,4,'list_item','Atenție, librăriile de cod și endpoint-urile API folosesc încă terminologia istorică <strong>Retail</strong> (ex: <code>google.cloud.retail_v2</code>).',NULL,NULL,NULL);
INSERT INTO elements VALUES(18,18,1,'list_item','Scripturi JS pentru site e-commerce.',NULL,NULL,NULL);
INSERT INTO elements VALUES(19,18,2,'list_item','Hooks în backend e-commerce, ERP, WMS sau CRM.',NULL,NULL,NULL);
INSERT INTO elements VALUES(20,18,3,'list_item','Logare în fișiere sau în topicuri (ex. Pub/Sub, Kafka).',NULL,NULL,NULL);
INSERT INTO elements VALUES(21,18,4,'list_item','Endpoint <code>API POST /recom Account_id=…&amp;Context=…</code>',NULL,NULL,NULL);
INSERT INTO elements VALUES(22,18,5,'list_item','Widget pe site e-commerce sau în aplicații interne.',NULL,NULL,NULL);
INSERT INTO elements VALUES(23,19,1,'list_item','<strong>Modelul</strong> selectat din lista Google. Ex: <em>Buy it Again</em> cu obiectivul de maximizat deja selectat.',NULL,NULL,NULL);
INSERT INTO elements VALUES(24,19,2,'list_item','<strong>Serving Controls</strong>. <em>Filter</em> (excludere - doar în varianta de căutare), <em>Boost</em> (promovare), <em>Bury</em> (retrogradare).',NULL,NULL,NULL);
INSERT INTO elements VALUES(25,19,3,'list_item','Setarea de <strong>diversitate</strong>: cât de non-repetitive sunt recomandările.',NULL,NULL,NULL);
INSERT INTO elements VALUES(26,19,4,'list_item','Chemi un <strong>ServingConfig</strong> când apelezi API, deci îl poți folosi pentru mai multe puncte de inserție în aplicațiile companiei dacă au aceleași reguli.',NULL,NULL,NULL);
INSERT INTO elements VALUES(27,19,5,'list_item','Serving Controls pot fi <strong>realizate ca fișiere JSON</strong>, deci refolosite în ServingConfigs de căutare diferite.',NULL,NULL,NULL);
INSERT INTO elements VALUES(28,25,1,'list_item','<strong>Ordonarea</strong> candidaților.',NULL,NULL,NULL);
INSERT INTO elements VALUES(29,25,2,'list_item','<strong>Post-procesare</strong> prin reguli de business (<a href="/ai-2026/ghid-recomandari-upsell/cum-tehnologie-recomandari-ai/#ai-control-post-processing-rules"><em>guardrails</em></a>). Pot fi de eliminare (en. <em>hard</em>), de ordonare (en. <em>soft</em>) sau de proces (ex: audit)',NULL,NULL,NULL);
INSERT INTO elements VALUES(30,25,3,'list_item','<strong>Livrarea finală</strong> a unei liste scurte de produse către aplicație în milisecunde (în scenarii optimizate).',NULL,NULL,NULL);
INSERT INTO elements VALUES(31,26,1,'list_item','semnale din <strong>catalog</strong>: preț, marjă, categorie, compatibilitate.',NULL,NULL,NULL);
INSERT INTO elements VALUES(32,26,2,'list_item','semnale de <strong>context</strong>: tip client, timp, detalii coș / ofertă.',NULL,NULL,NULL);
INSERT INTO elements VALUES(33,26,3,'list_item','Filtrează produse fără stoc sau sub marja minimă.',NULL,NULL,NULL);
INSERT INTO elements VALUES(34,26,4,'list_item','Promovează anumite produse sau campanii.',NULL,NULL,NULL);
INSERT INTO elements VALUES(35,26,5,'list_item','Asigură deduplicare și diversitate. Ex: "fără 3 produse consecutive de la același brand".',NULL,NULL,NULL);
INSERT INTO elements VALUES(36,27,1,'list_item',unistr('Fiecare control are structura de condiție / efect (ex: în CEL - Common Expression Language).\u000d\u000a                            Ceea ce te reîntoarce la definirea schemei.'),NULL,NULL,NULL);
INSERT INTO elements VALUES(37,27,2,'list_item',unistr('De exemplu, pentru a implementa o regulă de prognoză temporală externă, \u000d\u000a                            poți crea în schemă un atribut <code>seasonal_score</code> (ex: 0.0-1.0) și apoi să definești un Boost.'),NULL,NULL,NULL);
INSERT INTO elements VALUES(38,27,3,'list_item','Atenție, adesea rămân unele reguli în middleware sau aplicație, de exemplu <strong>permisiunile</strong>.',NULL,NULL,NULL);
INSERT INTO elements VALUES(39,34,1,'list_item','Grup A = situația precedentă.',NULL,NULL,NULL);
INSERT INTO elements VALUES(40,34,2,'list_item','Grup B = aplicare algoritmi noi.',NULL,NULL,NULL);
INSERT INTO elements VALUES(41,34,3,'list_item','Evoluția KPI-urilor de business (vezi mai sus).',NULL,NULL,NULL);
INSERT INTO elements VALUES(42,34,4,'list_item','Distribuția statistică a recomandărilor: procent bestsellers, diversitate per brand /  preț / categorie.',NULL,NULL,NULL);
INSERT INTO elements VALUES(43,34,5,'list_item','Intervențiile regulilor de business (guardrails) și al mecanismelor de fallback',NULL,NULL,NULL);
INSERT INTO elements VALUES(44,35,1,'list_item','Schimbi obiectivele și strategiile fără a modifica codul programat.',NULL,NULL,NULL);
INSERT INTO elements VALUES(45,35,2,'list_item','Analizezi rezultatele în dashboarduri vizuale.',NULL,NULL,NULL);
INSERT INTO elements VALUES(46,35,3,'list_item','Ajustezi în funcție de KPI (de obicei de business).',NULL,NULL,NULL);
INSERT INTO elements VALUES(47,37,1,'list_item',unistr('<strong>\u000d\u000a                                Deep Learning nu este un singur proces, ci o succesiune de pași:\u000d\u000a                            </strong>\u000d\u000a\u000d\u000a                            definirea obiectivelor, curățarea și conectarea datelor, definirea evenimentelor,\u000d\u000a                            generarea candidaților, ranking și post-procesare, integrare în UX, feedback explicit, monitorizare.'),NULL,NULL,NULL);
INSERT INTO elements VALUES(48,37,2,'list_item',unistr('<strong>\u000a<i class="fa-regular fa-gear icon-gradient"></i> Build (custom)\u000d\u000a                            </strong>\u000d\u000a\u000d\u000a                            oferă control maxim, dar cere echipă tehnică dedicată și disciplinată, în plus față de\u000d\u000a                            efortul întregii companii.'),NULL,NULL,NULL);
INSERT INTO elements VALUES(49,37,3,'list_item',unistr('<strong>\u000a<i class="fa-regular fa-cloud icon-gradient"></i> Managed (Cloud Native)\u000d\u000a                            </strong>\u000d\u000a\u000d\u000a                            externalizează o parte din complexitate, dar necesită decizii la nivelul companiei și\u000d\u000a                            configurare tehnică atentă.'),NULL,NULL,NULL);
INSERT INTO elements VALUES(50,37,4,'list_item','Ambele variante depind de curățarea datelor și <code>A/B testing</code> pentru a obține rezultate.',NULL,NULL,NULL);
INSERT INTO elements VALUES(51,39,1,'list_item','Exemplele sunt în pseudocod, pentru a <strong>arăta în practică</strong> câteva bucăți cheie de logică recomandări AI.',NULL,NULL,NULL);
INSERT INTO elements VALUES(52,39,2,'list_item',unistr('Pentru volume mari de date (Big Data) logica tinde să se mute din <strong><code>Python</code></strong> în <strong><code>Spark</code></strong> sau <strong><code>SQL</code></strong>\u000d\u000a                            pentru a evita iterări pe milioane de produse. Vezi exemple la <a href="#market-basket-analysis-spark-sql">Cap 4.2.4</a>.'),NULL,NULL,NULL);
INSERT INTO elements VALUES(53,39,3,'list_item','<em>Exemplele de cod sunt simplificate pentru claritate și necesită adaptare la mediul de producție specific, plus <strong>autentificare/IAM, protecție pentru concurență, excepții, reîncercări</strong> etc.</em>',NULL,NULL,NULL);
INSERT INTO elements VALUES(54,41,1,'code_snippet',unistr('from dataclasses import dataclass\u000d\u000a\u000d\u000a@dataclass\u000d\u000aclass Candidate:\u000d\u000a    sku: str\u000d\u000a    score_ai: float\u000d\u000a    stock: int\u000d\u000a    margin_pct: float\u000d\u000a    forbidden: bool = False\u000d\u000a\u000d\u000adef apply_guardrails(\u000d\u000a    candidates: list[Candidate],\u000d\u000a    min_margin_pct: float,\u000d\u000a    min_score_ai: float,\u000d\u000a    max_items: int = 10,\u000d\u000a) -> list[Candidate]:\u000d\u000a    # 1. filtram produsele interzise, fara stoc sau sub marja minima\u000d\u000a    filtered = [\u000d\u000a        c for c in candidates\u000d\u000a        if not c.forbidden\u000d\u000a        and c.stock > 0\u000d\u000a        and c.margin_pct >= min_margin_pct\u000d\u000a        and c.score_ai >= min_score_ai\u000d\u000a    ]\u000d\u000a\u000d\u000a    # 2. daca dupa filtrare lista este prea scurta, completam cu fallback intern (get_top_selling_products)\u000d\u000a    if len(filtered) < max_items:\u000d\u000a        missing = max_items - len(filtered)\u000d\u000a        exclude_skus = {c.sku for c in filtered}\u000d\u000a        filtered.extend(get_top_selling_products(exclude_skus=exclude_skus, limit=missing))\u000d\u000a    # 3. sortam dupa scorul AI și limitam\u000d\u000a    filtered.sort(key=lambda c: c.score_ai, reverse=True)\u000d\u000a    return filtered[:max_items]'),NULL,unistr('Snippet: pipeline care primește candidați cu scor și aplică guardrails\u000d\u000a                            înainte de a trimite către UI'),'{"language": "python"}');
INSERT INTO elements VALUES(55,41,2,'note_item',unistr('Guardrails sunt o\u000d\u000a\u000d\u000a                                <strong>\u000d\u000a                                    funcție distinctă\u000d\u000a                                </strong>\u000d\u000a\u000d\u000a                                în pipeline.'),NULL,'Note',NULL);
INSERT INTO elements VALUES(56,41,3,'note_item',unistr('<strong>\u000d\u000a                                    Fallback\u000d\u000a                                </strong>\u000d\u000a\u000d\u000a                                (pasul 2) e la fel de important ca filtrarea.'),NULL,'Note',NULL);
INSERT INTO elements VALUES(57,41,4,'note_item','Asigurați-vă că  <code>get_top_selling_products()</code> aplică aceleași guardrails',NULL,'Note',NULL);
INSERT INTO elements VALUES(58,42,1,'list_item',unistr('Pe lângă filtrele la runtime, poți face verificări offline care detectează\u000d\u000a                        recomandările nedorite (ex: cu marjă negativă).'),NULL,NULL,NULL);
INSERT INTO elements VALUES(59,42,2,'code_snippet',unistr('SELECT\u000d\u000a  r.account_id\u000d\u000a  , r.scenario\u000d\u000a  , r.sku_recomandat\u000d\u000a  , r.score_ai\u000d\u000a  , p.margin_pct\u000d\u000a  , r.created_at\u000d\u000aFROM recommendations_log r\u000d\u000aJOIN products p ON r.sku_recomandat = p.sku\u000d\u000aWHERE \u000d\u000a  p.margin_pct <= 0.15 -- sau prag parametrizabil\u000d\u000a  AND r.created_at > (NOW() - INTERVAL ''1 DAY'')\u000d\u000aORDER BY r.created_at DESC\u000d\u000aLIMIT 100;'),NULL,'Snippet: pseudocod de detecție recomandări cu marjă sub prag','{"language": "sql"}');
INSERT INTO elements VALUES(60,42,3,'note_item',unistr('Acest tip de interogări generează un\u000d\u000a\u000d\u000a                                <strong>\u000d\u000a                                    raport al calității\u000d\u000a                                </strong> într-un dashboard de analiză.'),NULL,'Note',NULL);
INSERT INTO elements VALUES(61,42,4,'note_item','Decizi în ce măsură guardrails-urile <strong>sunt suficiente sau mai trebuie definite</strong>.',NULL,'Note',NULL);
INSERT INTO elements VALUES(62,43,1,'list_item',unistr('Fără ingestie corectă, recomandările vor fi greșite. Pe lângă problema latenței, este importantă\u000d\u000a                        consistența datelor, toate evenimentele trebuie să aibă detaliile minime și să fie identificate unic pentru idempotență.'),NULL,NULL,NULL);
INSERT INTO elements VALUES(63,43,2,'code_snippet',unistr('from pydantic import BaseModel, Field\u000d\u000afrom datetime import datetime\u000d\u000afrom typing import Optional\u000d\u000a\u000d\u000aclass InventoryUpdateEvent(BaseModel):\u000d\u000a    sku: str\u000d\u000a    new_stock: int = Field(ge=0)\u000d\u000a    source: Optional[str] = None     # ex: "WMS", "ERP", "Manual"\u000d\u000a    updated_at: datetime\u000d\u000a    idempotency_key: str = Field(min_length=8)\u000d\u000a\u000d\u000a    #aici se poate adauga logica de Feature (atribut) pentru care apoi se defineste pipeline-ul'),NULL,'Snippet: structură de eveniment de actualizare stoc, validat înainte de pipeline / Feature Store','{"language": "python"}');
INSERT INTO elements VALUES(64,43,3,'note_item','Validează datele minime (<code>new_stock</code> nu e negativ) și permite ingestia în orice ordine prin <em>updated_at</em>.',NULL,'Note',NULL);
INSERT INTO elements VALUES(65,43,4,'note_item','În B2B <code>new_stock</code> trebuie calculat de obicei ca stoc real (scriptic - rezervat) sau chiar liber la raft (din WMS).',NULL,'Note',NULL);
INSERT INTO elements VALUES(66,43,5,'note_item','<em>idempotency_key</em> asigură că la retry/trimitere dublată a aceluiași update de stoc, sistemul îl poate procesa o singură dată.',NULL,'Note',NULL);
INSERT INTO elements VALUES(67,44,1,'code_snippet',unistr('INSERT INTO inventory (sku, stock, updated_at)\u000d\u000aVALUES (:sku, :stock, :updated_at)\u000d\u000aON CONFLICT (sku)\u000d\u000aDO UPDATE SET\u000d\u000a  stock = EXCLUDED.stock\u000d\u000a  , updated_at = EXCLUDED.updated_at\u000d\u000aWHERE \u000d\u000a    inventory.updated_at IS NULL \u000d\u000a    OR inventory.updated_at < EXCLUDED.updated_at;'),NULL,'Snippet: pseudocod de Postgres pentru actualizare stoc. În BigQuery folosiți MERGE','{"language": "sql"}');
INSERT INTO elements VALUES(68,44,2,'note_item','Idempotența se poate implementa suplimentar cu un tabel de deduplicare sau un câmp (Ex: <em>last_event_id</em>).',NULL,'Note',NULL);
INSERT INTO elements VALUES(69,44,3,'note_item','Poți determina dacă produsul e eligibil pentru recomandări (<em>stock &gt; 0</em>) și îl marchezi.',NULL,'Note',NULL);
INSERT INTO elements VALUES(70,44,4,'note_item','În caz de modificare, declanșezi un task care invalidează cache-ul local pentru el.',NULL,'Note',NULL);
INSERT INTO elements VALUES(71,45,1,'code_snippet',unistr('SELECT\u000d\u000a  i.sku\u000d\u000a  , i.stock AS stock_official\u000d\u000a  , c.stock_cache AS stock_recommender\u000d\u000aFROM inventory i\u000d\u000aJOIN recommender_cache c ON i.sku = c.sku\u000d\u000aWHERE i.stock <> c.stock_cache;'),NULL,'Snippet: pseudocod pentru detecția diferențelor între stocul oficial și cache-ul local de recomandări','{"language": "sql"}');
INSERT INTO elements VALUES(72,45,2,'note_item',unistr('Investighezi unde ingestia real-time nu funcționează. Ex: update-uri\u000d\u000a                                pierdute, update-uri netrimise.'),NULL,'Note',NULL);
INSERT INTO elements VALUES(73,45,3,'note_item','Este recomandat ca sistemul să detecteze problemele înainte ca ele să fie raportate de clienți sau agenți.',NULL,'Note',NULL);
INSERT INTO elements VALUES(74,47,1,'code_snippet',unistr('from enum import Enum\u000d\u000a\u000d\u000aclass Scenario(Enum):\u000d\u000a    SIMILAR_ITEMS = "similar_items"\u000d\u000a    CART_ADDONS = "cart_addons"\u000d\u000a    SUBSTITUTES = "substitutes"\u000d\u000a\u000d\u000a# Registry de mapare scenariu -> model\u000d\u000aMODEL_REGISTRY = {\u000d\u000a    Scenario.SIMILAR_ITEMS:  "models/similar_items_v3",\u000d\u000a    Scenario.CART_ADDONS:    "models/cart_addons_v5",\u000d\u000a    Scenario.SUBSTITUTES:    "models/substitutes_v2",\u000d\u000a}\u000d\u000a\u000d\u000a# Daca folosesti un Feature Store, poti avea un registry separat pentru versiunile serviciilor scenariilor\u000d\u000aFS_SERVICE_REGISTRY = {\u000d\u000a    Scenario.SIMILAR_ITEMS:  "similar_items_service_v1",\u000d\u000a    Scenario.CART_ADDONS:    "cart_addons_service_v2",\u000d\u000a    Scenario.SUBSTITUTES:    "substitutes_service_v1",\u000d\u000a}\u000d\u000a\u000d\u000adef recommend_for_scenario(\u000d\u000a    scenario: Scenario,\u000d\u000a    account_id: str,\u000d\u000a    context: dict,\u000d\u000a) -> list[str]:\u000d\u000a    model_path = MODEL_REGISTRY[scenario]\u000d\u000a    \u000d\u000a    full_context = context.copy()\u000d\u000a    # interactiune cu Feature store (conceptual): mai intai obtii detaliile din store, apoi hidratezi contextul\u000d\u000a    # fs_service = FS_SERVICE_REGISTRY[scenario]\u000d\u000a    # account_features = call_fs_to_get_features(account_id=account_id, service=fs_service)\u000d\u000a    # full_context.update(account_features)\u000d\u000a\u000d\u000a    # Apel catre un model local sau un endpoint din cloud (cu toate datele necesare)\u000d\u000a    scores = call_model(model_path, account_id=account_id, inputs=full_context)\u000d\u000a    \u000d\u000a\u000d\u000a    # scores e lista de (sku, score_ai), ex: [("SKU1", 0.92), ("SKU2", 0.87)...]\u000d\u000a    ordered = sorted(scores, key=lambda x: x[1], reverse=True)\u000d\u000a    return [sku for sku, _ in ordered]'),NULL,'Snippet: router care decide modelul și sursa de date în funcție de context, cu variantă Feature Store','{"language": "python"}');
INSERT INTO elements VALUES(75,47,2,'note_item',unistr('<strong>Organizarea versiunilor de modele și servicii</strong> este esențială și e bine să fie decuplată.\u000d\u000a                        Dacă nu știi ce versiune rulează într-un scenariu, nu poți explica ce se întâmplă în producție.'),NULL,'Note',NULL);
INSERT INTO elements VALUES(76,47,3,'note_item','Prin hidratare afli foarte rapid înainte de inferența modelului ultimele atribute din Feature Store pentru acel account_id.',NULL,'Note',NULL);
INSERT INTO elements VALUES(77,47,4,'note_item','Logica de Feature Store este ascunsă, contractul <code>call_fs_to_get_features</code> include conectarea, caching și deserializarea (pentru latență minimă).',NULL,'Note',NULL);
INSERT INTO elements VALUES(78,48,1,'code_snippet',unistr('scenarios:\u000d\u000a  similar_items:\u000d\u000a    model: "models/similar_items_v3"\u000d\u000a    max_items: 10\u000d\u000a\u000d\u000a  cart_addons:\u000d\u000a    model: "models/cart_addons_v5"\u000d\u000a    max_items: 6\u000d\u000a\u000d\u000a  substitutes:\u000d\u000a    model: "models/substitutes_v2"\u000d\u000a    max_items: 5'),NULL,'Snippet: configurație de scenariu într-un fișier declarativ ( JSON  sau  YAML ), ușor de modificat de  arhitect sau product owner (vezi Cap.5.2.1)','{"language": "yaml"}');
INSERT INTO elements VALUES(79,48,2,'note_item','Router-ul din exemplul anterior poate citi această configurație la startup.',NULL,'Note',NULL);
INSERT INTO elements VALUES(80,48,3,'note_item','Poți folosi principii de <em>Convention over Configuration</em> (ex: numele scenariului să corespundă numelui modelului, <em>similar_items</em> să fie și în numele store-ului de audit etc).',NULL,'Note',NULL);
INSERT INTO elements VALUES(81,49,1,'list_item',unistr('În\u000d\u000a\u000d\u000a                            <strong>\u000d\u000a                                sistemul de recomandare:\u000d\u000a                            </strong>\u000d\u000a\u000d\u000a                            ce pachet propun pentru coșul sau oferta curentă.'),NULL,NULL,NULL);
INSERT INTO elements VALUES(82,49,2,'list_item','În <strong>data warehouse</strong>: ce propuneri recomandăm să devină pachete permanente în aplicație.',NULL,NULL,NULL);
INSERT INTO elements VALUES(83,51,1,'list_item',unistr('<details class="ais_codeblock">\u000a<summary class="ais_codeblock__summary">\u000d\u000a                            Snippet: algoritm FPGrowth (Frequent Pattern Growth) pentru a găsi asocieri\u000d\u000a                        </summary>\u000a<pre class="ais_codeblock__pre"><code class="language-python" data-lang="python">\u000d\u000afrom pyspark.ml.fpm import FPGrowth\u000d\u000afrom pyspark.sql import SparkSession\u000d\u000a\u000d\u000aspark = SparkSession.builder.getOrCreate()\u000d\u000a\u000d\u000a# 1. Datele: fiecare rand este o tranzactie cu un array de SKU\u000d\u000a# schema: [order_id: string, items: array&lt;string&gt;]\u000d\u000adf_orders = spark.table("sales_history_clean")\u000d\u000a\u000d\u000a# 2. Configuram algoritmul FPGrowth\u000d\u000a# minSupport: produsele apar impreuna in X% din tranzactii\u000d\u000a# minConfidence: cine ia A, are X% sanse sa ia si B\u000d\u000afp_growth = FPGrowth(itemsCol="items", minSupport=0.001, minConfidence=0.2)\u000d\u000a\u000d\u000a# 3. Antrenam modelul distribuit\u000d\u000amodel = fp_growth.fit(df_orders)\u000d\u000a\u000d\u000a# 4. Extragem regulile de asociere (antecedent -&gt; consequent)\u000d\u000a# schema: [antecedent: [SKU_A], consequent: [SKU_B], confidence: 0.85, lift: 2.4]\u000d\u000aassociation_rules = model.associationRules\u000d\u000a\u000d\u000a# Salvam intr-un tabel temporar pentru procesare ulterioara\u000d\u000aassociation_rules.createOrReplaceTempView("raw_rules")\u000d\u000a    </code>\u000d\u000a    </pre>\u000a</details>\u000a<details class="ais_codeblock ais_codeblock--teal">\u000a<summary class="ais_codeblock__summary">\u000a<strong>Note</strong>\u000a</summary>\u000a<ul class="ais_codeblock__p">\u000a<li>Acest cod rulează distribuit pe un cluster de Spark (pentru o implementare Enterprise) și procesează istoricul rapid.</li>\u000a<li>Rezultatul brut trebuie rafinat cu reguli de business (guardrails) ulterior. </li>\u000a<li>În pre-procesare se pot îndepărta produsele prea comune care sunt zgomot statistic (en. <em>noise</em>): ambalaje, consumabile, transportul dacă are SKU în ERP. </li>\u000a</ul>\u000a</details>'),NULL,NULL,NULL);
INSERT INTO elements VALUES(84,51,2,'code_snippet',unistr('from pyspark.ml.fpm import FPGrowth\u000d\u000afrom pyspark.sql import SparkSession\u000d\u000a\u000d\u000aspark = SparkSession.builder.getOrCreate()\u000d\u000a\u000d\u000a# 1. Datele: fiecare rand este o tranzactie cu un array de SKU\u000d\u000a# schema: [order_id: string, items: array<string>]\u000d\u000adf_orders = spark.table("sales_history_clean")\u000d\u000a\u000d\u000a# 2. Configuram algoritmul FPGrowth\u000d\u000a# minSupport: produsele apar impreuna in X% din tranzactii\u000d\u000a# minConfidence: cine ia A, are X% sanse sa ia si B\u000d\u000afp_growth = FPGrowth(itemsCol="items", minSupport=0.001, minConfidence=0.2)\u000d\u000a\u000d\u000a# 3. Antrenam modelul distribuit\u000d\u000amodel = fp_growth.fit(df_orders)\u000d\u000a\u000d\u000a# 4. Extragem regulile de asociere (antecedent -> consequent)\u000d\u000a# schema: [antecedent: [SKU_A], consequent: [SKU_B], confidence: 0.85, lift: 2.4]\u000d\u000aassociation_rules = model.associationRules\u000d\u000a\u000d\u000a# Salvam intr-un tabel temporar pentru procesare ulterioara\u000d\u000aassociation_rules.createOrReplaceTempView("raw_rules")'),NULL,'Snippet: algoritm FPGrowth (Frequent Pattern Growth) pentru a găsi asocieri','{"language": "python"}');
INSERT INTO elements VALUES(85,51,3,'note_item','Acest cod rulează distribuit pe un cluster de Spark (pentru o implementare Enterprise) și procesează istoricul rapid.',NULL,'Note',NULL);
INSERT INTO elements VALUES(86,51,4,'note_item','Rezultatul brut trebuie rafinat cu reguli de business (guardrails) ulterior.',NULL,'Note',NULL);
INSERT INTO elements VALUES(87,51,5,'note_item','În pre-procesare se pot îndepărta produsele prea comune care sunt zgomot statistic (en. <em>noise</em>): ambalaje, consumabile, transportul dacă are SKU în ERP.',NULL,'Note',NULL);
INSERT INTO elements VALUES(88,52,1,'list_item','După ce există asocierile, logica sistemului de recomandări se aplică prin verificări. Exemplificăm cu <code>SQL</code> peste <code>Spark</code> un caz complex:',NULL,NULL,NULL);
INSERT INTO elements VALUES(89,52,2,'list_item','Există tabelul de asocieri între pachete (antecedent) care pot avea mai multe produse și un singur produs recomandat (consequent).',NULL,NULL,NULL);
INSERT INTO elements VALUES(90,52,3,'list_item','Verificăm că produsele nu au fost șterse, au preț și cele asociate (consequent) au stoc > 10.',NULL,NULL,NULL);
INSERT INTO elements VALUES(91,52,4,'list_item','Calculăm marja totală a asocierii (antecedent + consequent).',NULL,NULL,NULL);
INSERT INTO elements VALUES(92,52,5,'list_item','Avantajăm dintre bundleurile cu marjă totală pozitivă pe cele cu un produs în stoc peste 120 de zile.',NULL,NULL,NULL);
INSERT INTO elements VALUES(93,52,6,'code_snippet',unistr('WITH rule_financials AS (\u000d\u000a    SELECT \u000d\u000a        r.antecedent\u000d\u000a        , r.consequent\u000d\u000a        , r.confidence\u000d\u000a        -- COALESCE pentru a evita NULL\u000d\u000a        , SUM(COALESCE(p_ant.margin_eur, 0)) as antecedent_total_margin        \u000d\u000a        -- Verificam daca am gasit toate produsele din antecedent\u000d\u000a        , COUNT(p_ant.sku) as found_ant_products\u000d\u000a        , SIZE(r.antecedent) as expected_ant_products\u000d\u000a        , MAX(COALESCE(p_cons.margin_eur, 0)) as consequent_margin\u000d\u000a        , MAX(p_cons.days_in_inventory) as cons_days_inv\u000d\u000a    FROM raw_rules r\u000d\u000a    LATERAL VIEW explode(r.antecedent) a AS ant_sku\u000d\u000a    -- JOIN pentru antecedent\u000d\u000a    JOIN products p_ant ON a.ant_sku = p_ant.sku  \u000d\u000a    -- JOIN pentru consequent cu filtrare directa de stoc > 10 \u000d\u000a    JOIN products p_cons ON r.consequent[0] = p_cons.sku AND p_cons.stock_quantity > 10\u000d\u000a    GROUP BY \u000d\u000a        r.antecedent\u000d\u000a        , r.consequent\u000d\u000a        , r.confidence\u000d\u000a)\u000d\u000a\u000d\u000aSELECT\u000d\u000a    antecedent as current_basket\u000d\u000a    , consequent[0] as recommended_upsell\u000d\u000a    , confidence\u000d\u000a    , (antecedent_total_margin + consequent_margin) as total_bundle_margin\u000d\u000a    -- Calcul scor\u000d\u000a    , (confidence \u000d\u000a        * (antecedent_total_margin + consequent_margin) \u000d\u000a        * (CASE WHEN cons_days_inv > 120 THEN 1.5 ELSE 1.0 END)\u000d\u000a        ) as priority_score\u000d\u000aFROM rule_financials\u000d\u000aWHERE \u000d\u000a    -- la JOIN nu s-au pierdut produse din antecedent \u000d\u000a    found_ant_products = expected_ant_products\u000d\u000a    -- eliminam marjele negative sau zero (recomandat)\u000d\u000a    AND (antecedent_total_margin + consequent_margin) > 0\u000d\u000aORDER BY \u000d\u000a    priority_score DESC;'),NULL,'Snippet: sortare pachete după marjă și stoc vechi cu verificări de consistență ( Hive / Spark )','{"language": "sql"}');
INSERT INTO elements VALUES(94,52,7,'note_item','Statistica "clienții cumpără A+B" se combină cu logica companiei: "vindem A+B pentru că B e pe stoc de 120 de zile".',NULL,'Note',NULL);
INSERT INTO elements VALUES(95,52,8,'note_item','Rezultatele din acest raport (ex: zilnic) pot deveni <a href="/ai-2026/ghid-recomandari-upsell/cum-tehnologie-recomandari-ai/#dynamic-product-bundling">pachete reale de vânzare în e-commerce sau afiliați (Cap. 2.6.2.2)</a>.',NULL,'Note',NULL);
INSERT INTO elements VALUES(96,53,1,'list_item',unistr('Când agentul construiește o ofertă, sistemul poate propune automat pachete pe baza listelor de\u000d\u000a                        bundle-uri:'),NULL,NULL,NULL);
INSERT INTO elements VALUES(97,53,2,'code_snippet',unistr('def suggest_bundles_for_quote(\u000d\u000a    current_skus: list[str],\u000d\u000a    bundles: dict[tuple[str, str], int],\u000d\u000a    max_suggestions: int = 5,\u000d\u000a) -> list[tuple[str, str]]:\u000d\u000a    suggestions: list[tuple[str, str]] = []\u000d\u000a    seen: set[tuple[str, str]] = set()\u000d\u000a    current = set(current_skus)\u000d\u000a\u000d\u000a    for sku in current_skus:\u000d\u000a        for (a, b), _count in bundles.items():\u000d\u000a            pair = None\u000d\u000a\u000d\u000a            if sku == a and b not in current:\u000d\u000a                pair = (a, b)\u000d\u000a            elif sku == b and a not in current:\u000d\u000a                pair = (b, a)\u000d\u000a\u000d\u000a            if pair and pair not in seen:\u000d\u000a                seen.add(pair)\u000d\u000a                suggestions.append(pair)\u000d\u000a\u000d\u000a                if len(suggestions) >= max_suggestions:\u000d\u000a                    break\u000d\u000a\u000d\u000a        if len(suggestions) >= max_suggestions:\u000d\u000a            break\u000d\u000a\u000d\u000a    return suggestions'),NULL,unistr('Snippet: pseudocod care atribuie produselor curente\u000d\u000a                            bundle-uri precalculate'),'{"language": "python"}');
INSERT INTO elements VALUES(98,53,3,'note_item',unistr('Compania nu mai depinde de <a href="/ai-2026/ghid-recomandari-upsell/cum-tehnologie-recomandari-ai/#manual-organizational-knowledge">\u000d\u000a                                memoria agentului (Gen 0)</a> pentru a propune cross-sell, AI identifică tipare și în post-procesare regulile validează și ordonează pachetele conform politicii comerciale.'),NULL,'Note',NULL);
INSERT INTO elements VALUES(99,53,4,'note_item','În producție, puteți indexa bundle-urile după SKU (hashmap) pentru a evita loop.',NULL,'Note',NULL);
INSERT INTO elements VALUES(100,53,5,'note_item','În producție, trebuie monitorizate 24/7 pipeline-urile de date și reîncercările (en. <em>retries</em>).',NULL,'Note',NULL);
PRAGMA writable_schema=ON;
CREATE TABLE IF NOT EXISTS sqlite_sequence(name,seq);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('pages',1);
INSERT INTO sqlite_sequence VALUES('sections',17);
INSERT INTO sqlite_sequence VALUES('blocks',57);
INSERT INTO sqlite_sequence VALUES('elements',100);
CREATE INDEX idx_sections_page   ON sections(page_id, sort_order);
CREATE INDEX idx_blocks_section  ON blocks(section_id, sort_order);
CREATE INDEX idx_elements_block  ON elements(block_id, sort_order);
PRAGMA writable_schema=OFF;
COMMIT;
